refactor decode logic, add file decoder.scala
shuosc/shuorv pull request #47
Opened 2022-10-09 11:24 UTC by AlwenXXD

**Problem Summary**: I think the readability of decode logic is a little bit poor, and hard to extend instructions.

**What's Changed**: Now most of contorl signal is defined in a table in file Decoder.scala using ChiselEnum.

**How it Works**: When add new modules or new instructions, you can esaily add instruction decode information and control signals in decode table.

2022-10-18 17:28 UTC, zhoudian64 approved these changes
LGTM, what's your opinion. @longfangsong

2022-10-18 17:35 UTC, longfangsong requested changes
Rest LGTM

2022-10-18 17:35 UTC, longfangsong commented on src/main/scala/ALU.scala
> +//  import ALUOperation._
Feel free to delete the code if you think they are not useful.

2022-10-18 17:35 UTC, longfangsong commented on src/main/scala/CPU.scala
>        // LB
You can remove the comments here if you use named `ChiselEnum`.

2022-10-18 17:35 UTC, longfangsong commented on src/main/scala/Decoder.scala
> +object uOP extends ChiselEnum {
I don't know whether `uOP` is the best name here...
However I don't have a better alternative.
Please at least make it `UOp`.

2022-10-18 17:35 UTC, longfangsong commented on src/main/scala/Decoder.scala
> +  //load,store
```suggestion
  //load, store
```

2022-10-18 17:35 UTC, longfangsong commented on src/main/scala/Decoder.scala
> +  val csr_idx  = UInt(12.W)
We prefer `camelCase` for names.

2022-10-18 18:28 UTC, longfangsong commented on src/main/scala/Decoder.scala
> +  def BEQ                = BitPat("b?????????????????000?????1100011")
We prefer `camelCase` for method names

2022-10-22 03:51 UTC, longfangsong approved these changes
LGTM, thank you for your contribution!

2022-10-22 03:52 UTC, merged